import types from "./types";

import Example from "./example.json";

import storage from "./storage";

window.onbeforeunload = storage.save;
window.onunload = storage.save;

//SYSTEM ACTIONS

export const showModal = (
  type = "waiting",
  content = null,
  actions = null,
  buttons = null
) => {
  return {
    type: types.SHOW_MODAL,
    payload: {
      display: true,
      type,
      content,
      actions,
      buttons
    }
  };
};
export const unshowModal = () => {
  return {
    type: types.UNSHOW_MODAL,
    payload: {
      display: false,
      type: null,
      message: null,
      buttons: null
    }
  };
};

//USER ACTIONS
export const exampleCollection = () => {
  storage.init("example");
  let collection = storage.set({
    id: "example",
    name: "Example",
    desc: "This is an Example Collection generated by Acadtable."
  });
  storage.setData(Example);
  return {
    type: types.EXAMPLE_COLLECTION,
    payload: collection
  };
};

export const createCollection = (data = {}, background = null) => {
  storage.init();
  let collection = storage.set(data);
  if (background != null) {
    return collection;
  }
  return {
    type: types.CREATE_COLLECTION,
    payload: collection
  };
};
export const selectCollection = id => {
  storage.init(id);
  return {
    type: types.SELECT_COLLECTION,
    payload: {
      user: storage,
      tables: storage.getDataKey("tables"),
      days: storage.getDataKey("days"),
      places: storage.getDataKey("places"),
      lectures: storage.getDataKey("lectures"),
      batches: storage.getDataKey("batches"),
      times: storage.getDataKey("times"),
      subjects: storage.getDataKey("subjects"),
      teachers: storage.getDataKey("teachers")
    }
  };
};

export const deselectCollection = () => {
  return {
    type: types.DESELECT_COLLECTION,
    payload: null
  };
};
export const copyCollection = id => {
  let newid = storage.init();
  let collection = storage.get(id);
  collection.name += " Copy";
  collection.id = newid;
  collection = storage.set(collection);
  storage.setData(storage.getData(id));
  return {
    type: types.COPY_COLLECTION,
    payload: collection
  };
};
export const renameCollection = (id, newname) => {
  return {
    type: types.RENAME_COLLECTION,
    payload: {}
  };
};
export const deleteCollection = id => {
  storage.init(id);
  let deleted = storage.delete();
  return {
    type: types.DELETE_COLLECTION,
    payload: deleted
  };
};

//TABLE ACTIONS

export const createTable = (data, background = null) => {
  let table = storage.setDataItem("tables", null, data);
  if (background !== null) {
    return table;
  }
  return {
    type: types.CREATE_TABLE,
    payload: table
  };
};
export const updateTable = (tableID, data) => {
  let table = storage.setDataItem("tables", tableID, data);
  return {
    type: types.UPDATE_TABLE,
    payload: table
  };
};
export const deleteTable = tableID => {
  let table = storage.delDataItem("tables", tableID);
  return {
    type: types.DELETE_TABLE,
    payload: table
  };
};

//Lecture ACTIONS

export const createLecture = data => {
  let lecture = storage.setDataItem("lectures", null, data);
  return {
    type: types.CREATE_LECTURE,
    payload: lecture
  };
};
export const updateLecture = (lectureID, data) => {
  let lecture = storage.setDataItem("lectures", lectureID, data);
  return {
    type: types.UPDATE_LECTURE,
    payload: lecture
  };
};
export const deleteLecture = lectureID => {
  let lecture = storage.delDataItem("lectures", lectureID);
  return {
    type: types.DELETE_LECTURE,
    payload: lecture
  };
};

//DAY ACTIONS

export const createDay = (data, background = null) => {
  let day = storage.setDataItem("days", null, data);
  if (background !== null) {
    return day;
  }
  return {
    type: types.CREATE_DAY,
    payload: day
  };
};
export const updateDay = (dayID, data) => {
  let day = storage.setDataItem("days", dayID, data);
  return {
    type: types.UPDATE_DAY,
    payload: day
  };
};
export const deleteDay = dayID => {
  let day = storage.delDataItem("days", dayID);
  return {
    type: types.DELETE_DAY,
    payload: day
  };
};

//TIME ACTIONS

export const createTime = (data, background = null) => {
  let time = storage.setDataItem("times", null, data);
  if (background !== null) {
    return time;
  }
  return {
    type: types.CREATE_TIME,
    payload: time
  };
};
export const updateTime = (timeID, data) => {
  let time = storage.setDataItem("times", timeID, data);
  return {
    type: types.UPDATE_TIME,
    payload: time
  };
};
export const deleteTime = timeID => {
  let time = storage.delDataItem("times", timeID);
  return {
    type: types.DELETE_TIME,
    payload: time
  };
};

//PLACE ACTIONS

export const createPlace = (data, background = null) => {
  let place = storage.setDataItem("places", null, data);
  if (background !== null) {
    return place;
  }
  return {
    type: types.CREATE_PLACE,
    payload: place
  };
};
export const updatePlace = (placeID, data) => {
  let place = storage.setDataItem("places", placeID, data);
  return {
    type: types.UPDATE_PLACE,
    payload: place
  };
};
export const deletePlace = placeID => {
  let place = storage.delDataItem("places", placeID);
  return {
    type: types.DELETE_PLACE,
    payload: place
  };
};

//BATCH ACTIONS

export const createBatch = data => {
  let batch = storage.setDataItem("batches", null, data);
  return {
    type: types.CREATE_BATCH,
    payload: batch
  };
};
export const updateBatch = (batchID, data) => {
  let batch = storage.setDataItem("batches", batchID, data);
  return {
    type: types.UPDATE_BATCH,
    payload: batch
  };
};
export const deleteBatch = batchID => {
  let batch = storage.delDataItem("batches", batchID);
  return {
    type: types.DELETE_BATCH,
    payload: batch
  };
};

//SUBJECT ACTIONS

export const createSubject = data => {
  let subject = storage.setDataItem("subjects", null, data);
  return {
    type: types.CREATE_SUBJECT,
    payload: subject
  };
};
export const updateSubject = (subjectID, data) => {
  let subject = storage.setDataItem("subjects", subjectID, data);
  return {
    type: types.UPDATE_SUBJECT,
    payload: subject
  };
};
export const deleteSubject = subjectID => {
  let subject = storage.delDataItem("subjects", subjectID);
  return {
    type: types.DELETE_SUBJECT,
    payload: subject
  };
};

//TEACHER ACTIONS

export const createTeacher = data => {
  let teacher = storage.setDataItem("teachers", null, data);
  return {
    type: types.CREATE_TEACHER,
    payload: teacher
  };
};
export const updateTeacher = (teacherID, data) => {
  let teacher = storage.setDataItem("teachers", teacherID, data);
  return {
    type: types.UPDATE_TEACHER,
    payload: teacher
  };
};
export const deleteTeacher = teacherID => {
  let teacher = storage.delDataItem("teachers", teacherID);
  return {
    type: types.DELETE_TEACHER,
    payload: teacher
  };
};
