export const CREATE_TABLE = "CREATE_TABLE";
export const SELECT_TABLE = "SELECT_TABLE";
export const RENAME_TABLE = "RENAME_TABLE";
export const DELETE_TABLE = "DELETE_TABLE";

export const CREATE_BATCH = "CREATE_BATCH";
export const RENAME_BATCH = "RENAME_BATCH";
export const DELETE_BATCH = "DELETE_BATCH";

export const CREATE_LECTURE = "CREATE_LECTURE";
export const RENAME_LECTURE = "RENAME_LECTURE";
export const DELETE_LECTURE = "DELETE_LECTURE";

export const CREATE_SUBJECT = "CREATE_SUBJECT";
export const RENAME_SUBJECT = "RENAME_SUBJECT";
export const DELETE_SUBJECT = "DELETE_SUBJECT";

export const CREATE_TEACHER = "CREATE_TEACHER";
export const RENAME_TEACHER = "RENAME_TEACHER";
export const DELETE_TEACHER = "DELETE_TEACHER";
